// Custom next/image loader for the static export.
// Maps /assets/<name>.jpg -> /assets/opt/<name>-<w>.webp (generated by scripts/optimize-images.mjs).
const WIDTHS = [384, 640, 960, 1280];

export default function imageLoader({ src, width }) {
  if (!src.startsWith('/assets/') || !/\.(jpe?g|png)$/i.test(src)) return src;
  const w = WIDTHS.find((x) => x >= width) ?? WIDTHS[WIDTHS.length - 1];
  const name = src.replace(/^\/assets\//, '').replace(/\.(jpe?g|png)$/i, '');
  return `/assets/opt/${name}-${w}.webp`;
}
